name: vpn_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  flutter_bloc: ^8.1.4
  shared_preferences: ^2.2.2
  get_it: ^7.6.7
  injectable: ^2.3.4
  auto_route: ^7.8.4
  flutter_native_splash: ^2.4.0
  device_info_plus: ^9.1.2
  package_info_plus: ^8.3.0
  logger: ^2.1.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  flutter_secure_storage: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  injectable_generator: ^2.4.1
  auto_route_generator: ^7.3.2
  flutter_gen_runner: ^5.4.0

flutter:
  uses-material-design: true
